### ISSUE TITLE
Cyclic namespace dependency detected when loading `covid19br`

### ISSUE THREAD

**Issue by mnunes** [paternogbc/covid19br#1]
I tried to install the package, but it fails everytime. 

    devtools::install_github(repo = "paternogbc/covid19br")
    Downloading GitHub repo paternogbc/covid19br@master
       checking DESCRIPTION meta-information ...c/8hj8csfj73j4l4w93r1f0_vw0000gn/T/RtmpTgvyBg/remotesf68f675f6a38/paternogbc-covid19br-5aaa3e4/DESCRIPTION’ ...
    * installing *source* package ‘covid19br’ ...
    ** using staged installation
    ** R
    ** data
    *** moving datasets to lazyload DB
    ** inst
    ** byte-compile and prepare package for lazy loading
    Error : package or namespace load failed for ‘covid19br’ in loadNamespace(package, lib.loc):
     cyclic namespace dependency detected when loading ‘covid19br’, already loading ‘covid19br’
    Error: unable to load R code in package ‘covid19br’
    Execution halted
    ERROR: lazy loading failed for package ‘covid19br’
    * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/covid19br’
    Error: Failed to install 'covid19br' from GitHub:
      (converted from warning) installation of package ‘/var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpTgvyBg/filef68f2936b78d/covid19br_0.1.0.tar.gz’ had non-zero exit status

Here ins my session info in case you need it:

    R version 3.6.3 (2020-02-29)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS Catalina 10.15.3
    
    Matrix products: default
    BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
    LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
    
    Random number generation:
     RNG:     L'Ecuyer-CMRG 
     Normal:  Inversion 
     Sample:  Rounding 
     
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
     [1] splines   grid      tools     compiler  stats     graphics  grDevices utils     datasets 
    [10] methods   base     
    
    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.4        remotes_2.1.1     prettyunits_1.1.1 testthat_2.3.2    pkgload_1.0.2    
     [6] pkgbuild_1.0.6    digest_0.6.25     memoise_1.1.0     nlme_3.1-145      lattice_0.20-40  
    [11] rlang_0.4.5       cli_2.0.2         withr_2.1.2       fs_1.3.2          desc_1.2.0       
    [16] devtools_2.2.2    rprojroot_1.3-2   glue_1.3.2        R6_2.4.1          processx_3.4.2   
    [21] fansi_0.4.1       sessioninfo_1.1.1 minqa_1.2.4       callr_3.4.2       magrittr_1.5     
    [26] usethis_1.5.1     backports_1.1.5   ellipsis_0.3.0    MASS_7.3-51.5     assertthat_0.2.1 
    [31] crayon_1.3.4

**Comment by paternogbc** [comment]
Hi @mnunes , thanks for reporting. It was a simple issue in the NAMESPACE. 
Could you please try again by:
```r
devtools::install_github(repo = "paternogbc/covid19br")
```
 I have updated and fixed the issue with this commit 93c68237a685b6d3348845bdd32fbf9c7ca6cd48.

I appreciate with could post here if the issue is fixed.

**Comment by mnunes** [comment]
Thank you, @paternogbc . The issue is fixed. You can close it. 

Thank you.

**Comment by paternogbc** [comment]
Thanks 👍
